### ISSUE TITLE
Your code wont start - atleast, it itsn't clear how to

### ISSUE THREAD

**Issue by agathver** [Anisha1234/Mark-Updater#1]
As an enthusiastic first-time user, I eagerly cloned your code to test it, and it was a really bumpy ride.

1. Your dependency on `nodemon` for `npm start` isn't documented and it's a bad idea to add external (read globally installed) scripts in nodejs. Note that `npm start` is expected to be used in production, so please don't use nodemon there.
2. You should never hardcode passwords, keys, API URLs and server hostnames. My MySQL hostname was different

**Comment by Rishav159** [comment]
Awww. You look so cute trying to undermine people!
